### ISSUE TITLE
remove .DS_Store

### ISSUE THREAD

**Issue by quaeritis** [OE-FET/keithleygui#2]
Hello Sam Schott,

First of all thanks for the great work.
Can you do the following:

git filter-branch --force --index-filter \
'git rm --cached --ignore-unmatch *.DS_Store' \
--prune-empty --tag-name-filter cat -- --all

git push origin --force --all

This should remove all .DS_Store from the repo and history.

Kind regards
quaeritis

**Comment by samschott** [comment]
Done
