### ISSUE TITLE
Type Error when trying to run keithleygui command

### ISSUE THREAD

**Issue by ghost** [OE-FET/keithleygui#21]
Hello - I am getting a type error when trying to run the keithleygui command, looks like it is coming from PyQt5 I believe. Please see error in image below:
![Screenshot_20220321_154347](https://user-images.githubusercontent.com/85794071/159352312-1822c8bb-dde6-4f54-ae54-af4eab31fba5.png)

**Comment by samschott** [comment]
@johnisprettyneat, this seems to be change in Python 3.10 which no longer type casts float -> int when passing the argument to an extension module. I expect that many places in the GUI that call PyQt5 methods will need to be updated.

I'm a bit short on time at the moment but I'm happy to review a PR I've you are willing to take this on.

**Comment by ghost** [comment]
@samschott Submitted a PR for the issue. I am not a developer by background so make sure I didn't mess anything up. Simply changed line 184 in pyqtplot_canvas.py file to pass in an integer instead of a float. After doing that locally the gui did open for me.

Now I just need to figure out how to get my Keithley unit to connect and communicate with the computer!

**Comment by samschott** [comment]
Thanks! I'll have a look at it.

Regarding connecting the Keithley, I've made good experiences with an ethernet connection, if you have a spare network card. Otherwise, the Help button in the Connection Settings pane will show some information about available backends and any additional Python packages to install for USB and Serial connections.

**Comment by ghost** [comment]
Awesome, I will close out this issue!

As far as connecting goes - haven't gotten it yet. Likely need to mess with some settings on the Keithley itself that I haven't figured out yet. I have tried 3 different connection variants; ethernet plugged directly into laptop, rs232-to-usb, and usb-to-usb, but haven't seen communication with the device thus far.

I am running on Arch and have tried both backends @py and iviz library installed from the aur. I also attempted via python REPL using the keithley2600 library and resource manager but same issue. Do you have any suggestions on what settings you put in the keithley to connect via ethernet?

**Comment by samschott** [comment]
@ghost, sorry for not getting back to you about this. Decent instrictions for different network setups are available here at https://download.tek.com/manual/2701-904-01D_Feb_2016.pdf.
