### ISSUE TITLE
sorry requirements.txt should also be removed, my mistake

### ISSUE THREAD

**Issue by quaeritis** [OE-FET/keithleygui#4]
sorry requirements.txt should also be removed. That was my mistake, actually the file should not be in the commit.

git filter-branch --force --index-filter
'git rm --cached --ignore-unmatch requirements.txt'
--prune-empty --tag-name-filter cat -- --all

git push origin --force --all

Unfortunately, such changes can not be made by pull request (as much as I know).

**Comment by samschott** [comment]
No worries, I removed it.
