### ISSUE TITLE
Test on macOS and Windows

### ISSUE THREAD

**Issue by samschott** [OE-FET/keithleygui#5]
Unfortunately I can currently only test on linux. Any feedback or experience from running keithleygui on macOS and especially Windows is more than welcome.

Edit: Some changes to the config module may be needed to run keithleygui on Windows.

**Comment by samschott** [comment]
@quaeritis Which platform are you using to run keithleygui and the driver?

**Comment by quaeritis** [comment]
I am developing under Linux but the measurements are currently under Windows

**Comment by samschott** [comment]
First compatibility issue addressed in commit https://github.com/OE-FET/keithley2600/pull/5/commits/7461cb579274dcfc16ae2b48fd7b3f98528d7a0d for Keithley driver: allows for selection of visa-backend other than pyvisa-py.
